### ISSUE TITLE
Create a sensor wrapper for MLX90640 thermal cameras

### ISSUE THREAD

**Issue by Conr86** [SFXRescue/sights#16]
At the moment there is no sensor wrapper for the thermal camera (MLX90640). The thermal camera grid on the interface does work with an AMG8833, so all that is needed is the sensor wrapper.
The MLX90640 driver seems to be a bit tricky to use, as it's written in C, but does provide a Python wrapper.

**Comment by WilliamsJack** [comment]
9f78acccbcabad5f331cc1c26c620c573b51e1a1 adds a basic MLX90640 wrapper. It's fully functional but doesn't output great colours with the current thermal camera graph.

I've opened #86 to track that slightly different issue.
